name: Codeception

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    name: PHP ${{ matrix.php-versions }} + ${{ matrix.operating-system }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    env:
        DEFAULT_COMPOSER_FLAGS: "--no-interaction --no-ansi --no-progress --no-suggest"
        
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.5.0
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, gd, imagick, zip, dom, mysql, fileinfo
        ini-values: post_max_size=256M
        tools: php-cs-fixer, phpunit
    
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare the application
      run: cp tests/.env.example.mysql tests/.env
    
    - name: Test with Codeception
      run: vendor/bin/codecept run
      env:
        DB_DSN: mysql:host=127.0.0.1;port=${{ job.services.mysql.ports['3306'] }};dbname=test
        DB_USER: root
        DB_PASSWORD: password
        SECURITY_KEY: abcde12345
        DEFAULT_SITE_URL: "http://snipcart-craft-plugin.test/index.php"
        FROM_EMAIL_NAME: Craft CMS
        FROM_EMAIL_ADDRESS: "info@craftcms.com"
